console.log(document.cookie);

document.cookie = "name=Ranjit1122334400"

document.cookie = "name2=Ranjit11223344002"

document.cookie = "name=Ranjit"

let key = prompt("Enter your key");

let value = prompt("Enter your value");

document.cookie = `${encodeURIComponent(key)}=${encodeURIComponent(value)}`;    

// If you want to decode this encodeURIComponent(key)}=${encodeURIComponent(value) then use 

// decodeURIComponent("abcd%3B")    like this abcd%3B it is a key generated by browser because we used ; in the key

// abcd;                            --> This is output

console.log(document.cookie);   